[tool.poetry]
name = "openrouter-runner-modal"
version = "0.1.0"
description = "OpenRouter runner on Modal backend"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
huggingface-hub = "^0.17.1"
modal = "^0.52.3594"
transformers = "^4.34.1"
bitsandbytes = "^0.41.1"
peft = "^0.5.0"
accelerate = "^0.23.0"
datasets = "^2.14.5"
scipy = "^1.11.3"
wandb = "^0.15.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 80

[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
no_strict_optional = true
